YAFADEI/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from posts.views import (
    AllPostsPageView,
    MyPostsPageView,
    add_new_post_view,
    handle404Error,
    handle500Error,
    homepage_view,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("tinymce/", include("tinymce.urls")),
    path("", homepage_view, name="homepage"),
    path("new/", add_new_post_view, name="new_post"),
    path("posts/", AllPostsPageView.as_view(), name="posts_page"),
    path("post/", include("posts.urls")),
    path("my_posts/", MyPostsPageView.as_view(), name="my_posts"),
    path("", include("users.urls")),
]

handler404 = handle404Error
handler500 = handle500Error

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path

from posts import views as posts_view

urlpatterns = [
    path("<slug:slug>/", posts_view.PostPageView.as_view(), name="post_page"),
    path("like/<slug:slug>/", posts_view.post_like_view, name="post_like"),
    path(
        "dislike/<slug:slug>/",
        posts_view.post_dislike_view,
        name="post_dislike",
    ),
    path(
        "edit/<slug:slug>/", posts_view.EditPostView.as_view(), name="edit_post"
    ),
    path(
        "delete/<slug:slug>/",
        posts_view.DeletePostIView.as_view(),
        name="delete_post",
    ),
    path("favorite/<slug:slug>/", posts_view.favorite_view, name="favorite"),
]

users/urls.py
from django.contrib.auth.views import (
    LogoutView,
    PasswordChangeDoneView,
    PasswordChangeView,
    PasswordResetCompleteView,
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.urls import path, reverse_lazy

from users.views import LoginUser, RegisterUser

app_name = "users"

urlpatterns = [
    path("signup/", RegisterUser.as_view(), name="register"),
    path("login/", LoginUser.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    # ИЗМЕНЕНИЕ ПАРОЛЯ
    path(
        "password-change/",
        PasswordChangeView.as_view(
            template_name="pages/users/password_change_form.html",
            success_url=reverse_lazy("users:password_change_done"),
        ),
        name="password_change",
    ),
    path(
        "password-change/done/",
        PasswordChangeDoneView.as_view(
            template_name="pages/users/password_change_done.html"
        ),
        name="password_change_done",
    ),
    # СБРОС ПАРОЛЯ
    path(
        "password-reset/",
        PasswordResetView.as_view(
            template_name="pages/users/password_reset_form.html",
            email_template_name="pages/users/password_reset_email.html",
            success_url=reverse_lazy("users:password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        PasswordResetDoneView.as_view(
            template_name="pages/users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="pages/users/password_reset_confirm.html",
            success_url=reverse_lazy("users:password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset/complete/",
        PasswordResetCompleteView.as_view(
            template_name="pages/users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from posts.models import Posts


class User(AbstractUser):
    """Расширенная модель пользователя"""

    class Meta:
        verbose_name = "Пользователи"
        verbose_name_plural = "Пользователи"
        ordering = ["id"]


class Subscription(models.Model):
    subscriber = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="subscriber",
        verbose_name="Подписчик",
    )

    subscribed_to = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="subscribed_to",
        verbose_name="Подписан на",
    )

    class Meta:
        verbose_name = "Подписки"
        verbose_name_plural = "Подписки"
        ordering = ["id"]


class FavoritePost(models.Model):

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="favorite_posts"
    )
    post = models.ForeignKey(Posts, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Избранные посты"
        verbose_name_plural = "Избранные посты"
        ordering = ["id"]

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class UserRegisterForm(UserCreationForm):
    """Форма для регистрации"""

    def __init__(self, *args, **kwargs):
        """Конструктор в котором убираем подсказки для полей ввода"""
        super(UserCreationForm, self).__init__(*args, **kwargs)
        self.fields["username"].help_text = ""
        self.fields["password1"].help_text = ""
        self.fields["password2"].help_text = ""

    email = forms.EmailField(max_length=200)

    class Meta:
        model = get_user_model()

        fields = ("username", "email", "password1", "password2")


class LoginUserForm(AuthenticationForm):
    """Форма для авторизации"""

    class Meta:
        model = get_user_model()

        fields = ("username", "password")

users/views.py
from django.conf import settings
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy
from django.views.generic import CreateView

from users.forms import LoginUserForm, UserRegisterForm


class RegisterUser(CreateView):
    """Вью для страницы регистрации"""

    form_class = UserRegisterForm
    template_name = "pages/users/register.html"
    success_url = reverse_lazy(settings.LOGIN_URL)


class LoginUser(LoginView):
    """Вью для страницы авторизации"""

    form_class = LoginUserForm
    template_name = "pages/users/login.html"

    def get_success_url(self):
        return reverse_lazy("homepage")

templates/pages/users/edit_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {{ form.media }}
</head>
<body>
<h1>Edit post</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.media }}
    {{ form.as_p }}
    <button type="submit">Изменить</button>
</form>

</body>
</html>

templates/pages/users/login.html
{% extends 'base.html' %}
{% load static %}
{% block links %}
<link rel="stylesheet" href="{% static 'login-page.css' %}">
{% endblock links %}

{% block title %}
<meta charset="UTF-8">
<title>Title</title>
{% endblock title %}

{% block menu %}
{% endblock menu %}

{% block content %}
<div class="container">
    <div class="square" style="--i:0;"></div>
    <div class="square" style="--i:1;"></div>
    <div class="square" style="--i:2;"></div>
    <div class="square" style="--i:3;"></div>
    <div class="square" style="--i:4;"></div>
    <div class="square" style="--i:5;"></div>
    <form method="post" class="container-line">

        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit" class="btn-log">Войти в аккаунт</button>
    </form>
</div>
{% endblock content %}

templates/pages/users/my_posts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>My posts</h1>

{% for post in posts %}
    <p>{{ post.title }}</p>
    <img src="{{ post.img.url }}" alt="" width="500px" height="500px">

    <span> ЛАЙКИ {{ post.like.count}} </span>
    <span> ДИЗЛАЙКИ {{ post.dislike.count}} </span>


    <form  method="GET" action="{% url 'edit_post' slug=post.slug %}">
        {% csrf_token %}
        <button type="submit"> Изменить </button>
    </form>

    <form  method="POST" action="{% url 'delete_post' slug=post.slug %}">
        {% csrf_token %}
        <button type="submit"> Удалить </button>
    </form>

    <br>
    <br>
    <br>
    <br>
{% endfor %}

</body>
</html>

templates/pages/users/password_change_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <p>Ваш пароль успешно изменен!</p>
    <a href="{% url 'homepage' %}">Вернуться на главную</a>
</body>
</html>

templates/pages/users/password_change_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Изменение пароля</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p><button type="submit">Сохранить</button></p>
</form>
</body>
</html>

templates/pages/users/password_reset_complete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>Пароль изменен</h1>

<p>Поздравляем! Вы успешно изменили пароль своего аккаунта. Используйте его для
  <a href="{% url 'users:login' %}">входа в систему</a>.</p>

</body>
</html>

templates/pages/users/password_reset_confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Новый пароль</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <p><button type="submit">Сохранить</button></p>
</form>
</body>
</html>

templates/pages/users/password_reset_done.html
{% load i18n %}



<p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

templates/pages/users/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

templates/pages/users/password_reset_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>Восставление пароля</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Восстановить пароль</button>
    </form>
</body>
</html>

templates/pages/users/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/pages/users/register.html
{% extends 'base.html' %}
{% load static %}

{% block links %}
<link rel="stylesheet" href="{% static 'login-page.css' %}">
{% endblock links %}

{% block title %}
<meta charset="UTF-8">
<title>Title</title>
{% endblock title %}

{% block menu %}
{% endblock menu %}

{% block content %}
<div class="container">
    <div class="square" style="--i:0;"></div>
    <div class="square" style="--i:1;"></div>
    <div class="square" style="--i:2;"></div>
    <div class="square" style="--i:3;"></div>
    <div class="square" style="--i:4;"></div>
    <div class="square" style="--i:5;"></div>
    <form method="post" class="container-line">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn-log">Зарегистрироваться</button>
    </form>
</div>
{% endblock content %}